using Avalonia.Threading;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Dock.Model.Mvvm.Controls;
using SqlPhanos.CodeFormatting;
using SqlPhanos.Enums;
using SqlPhanos.ScriptDatabases;
using SqlPhanos.Services;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace SqlPhanos.ViewModels;

/// <summary>
/// A single "script every selected database on this connection to disk" session, ported from
/// ScriptyGuy's MainViewModel/DBConnectionInfo orchestration (state model reused, mechanism
/// rewritten to be CommunityToolkit.Mvvm-based and tab-owned like every other document in this
/// app). Deliberately does not persist database selections across sessions - every time this
/// document opens, its database list is freshly loaded with everything checked.
/// </summary>
public partial class ScriptDatabasesDocumentViewModel : Document, IHasTabHeaderLines
{
	private readonly DatabaseCatalogueService _catalogueService = new();
	private readonly DatabaseScriptingService _scriptingService = new();
	private readonly SqlCanonicalizationService _sqlCanonicalizationService = new();
	private readonly string _connectionString;
	private string _actualServerName = "";

	private CancellationTokenSource? _cts;
	private TaskCompletionSource<bool>? _encryptedConsentTcs;
	private TaskCompletionSource<ScriptOutputConflictChoice>? _outputConflictTcs;
	// Signaled when ScriptAsync's own finally block flips IsRunning back to false - lets
	// ConfirmCloseWhileRunningAsync wait for the in-flight run to actually stop after Cancel()
	// (which only requests cancellation; it doesn't itself wait for anything).
	private TaskCompletionSource? _operationCompletionTcs;
	private TaskCompletionSource<bool>? _closeConfirmationTcs;

	[ObservableProperty]
	[NotifyPropertyChangedFor(nameof(TabIconState))]
	[NotifyCanExecuteChangedFor(nameof(ScriptCommand))]
	[NotifyCanExecuteChangedFor(nameof(CancelCommand))]
	private bool _isRunning;

	[ObservableProperty]
	[NotifyPropertyChangedFor(nameof(TabIconState))]
	private bool _isInErrorState;

	[ObservableProperty]
	private string _status = "Connecting...";

	[ObservableProperty]
	private string _durationText = "";

	[ObservableProperty]
	private double _overallProgressPercent;

	[ObservableProperty]
	private string _baseOutputDirectory = "";

	[ObservableProperty]
	private bool _reformatSqlCode;

	[ObservableProperty]
	private bool _normalizeAutoGeneratedNames;

	[ObservableProperty]
	private bool _pendingEncryptedConsent;

	[ObservableProperty]
	private string _pendingEncryptedScopeDescription = "";

	[ObservableProperty]
	private int _pendingEncryptedCount;

	[ObservableProperty]
	private bool _pendingOutputConflict;

	[ObservableProperty]
	private string _pendingOutputConflictFolders = "";

	// Shown when the user tries to close this tab (X, Ctrl+W, or the Close Document menu item)
	// while a run is in progress - see OnClose().
	[ObservableProperty]
	private bool _pendingCloseConfirmation;

	// Per-object warnings surfaced during a run - currently just SqlCanonicalizationService's own
	// round-trip safety check rejecting a reformatted object (see IsRoundTripSafe) and keeping
	// that object's original, unformatted text instead. Shown in a list on the tab itself rather
	// than a blocking pop-over, since ScriptAsync can format hundreds of objects concurrently -
	// a modal per object would make the run unusable.
	public ObservableCollection<FormattingWarning> Warnings { get; } = new();

	public bool HasWarnings => Warnings.Count > 0;

	public string ConnectionDisplayName { get; }

	public ObservableCollection<DatabaseListItem> Databases { get; } = new();

	public bool CanRunScript => !IsRunning;

	// IHasTabHeaderLines - see SqlDocumentViewModel's identical implementation for why.
	public string TabHeaderLine1 => ConnectionDisplayName;

	public string TabHeaderLine2 => "Script Databases";

	public DocumentTabIconState TabIconState =>
		IsRunning ? DocumentTabIconState.Busy :
		IsInErrorState ? DocumentTabIconState.Error :
		DocumentTabIconState.None;

	// Parameterless constructor exists only for the XAML Design.DataContext tag, matching the
	// same pattern SqlDocumentViewModel/QueryXLeratorDocumentViewModel already use.
	public ScriptDatabasesDocumentViewModel()
	{
		_connectionString = "";
		ConnectionDisplayName = "";
		Title = "Script Databases";
		Warnings.CollectionChanged += (_, _) => OnPropertyChanged(nameof(HasWarnings));
	}

	public ScriptDatabasesDocumentViewModel(string connectionString, string connectionDisplayName)
	{
		_connectionString = connectionString;
		ConnectionDisplayName = connectionDisplayName;
		Title = $"Script Databases - {connectionDisplayName}";
		Warnings.CollectionChanged += (_, _) => OnPropertyChanged(nameof(HasWarnings));
		_ = LoadDatabasesAsync();
	}

	private async Task LoadDatabasesAsync()
	{
		IsRunning = true;
		IsInErrorState = false;
		Status = "Connecting...";

		var cts = new CancellationTokenSource();
		_cts = cts;
		try
		{
			var catalogue = await _catalogueService.LoadCatalogueAsync(_connectionString, cts.Token);
			_actualServerName = string.IsNullOrWhiteSpace(catalogue.ActualServerName)
				? ConnectionDisplayName
				: catalogue.ActualServerName;
			Databases.Clear();
			foreach (var name in catalogue.UserDatabases)
			{
				Databases.Add(new DatabaseListItem(name, isSelected: true));
			}

			Status = Databases.Count == 0
				? "No user databases found."
				: $"{Databases.Count} database(s) found.";
		}
		catch (OperationCanceledException)
		{
			Status = "Cancelled.";
		}
		catch (Exception ex)
		{
			IsInErrorState = true;
			Status = $"Unable to connect: {ex.Message}";
		}
		finally
		{
			_cts = null;
			IsRunning = false;
		}
	}

	[RelayCommand]
	private void CheckAll()
	{
		foreach (var item in Databases)
		{
			item.IsSelected = true;
		}
	}

	[RelayCommand]
	private void UncheckAll()
	{
		foreach (var item in Databases)
		{
			item.IsSelected = false;
		}
	}

	// Purely cosmetic - lets the user see which databases are running without scrolling, since a
	// long unattended run otherwise buries the active DB wherever it happened to sort originally.
	// Doesn't affect scripting order: targets is already captured (as references to the same
	// DatabaseListItem instances) before this runs, from the caller's own Databases.Where(...).
	private void ReorderCheckedFirst()
	{
		var ordered = Databases.OrderByDescending(item => item.IsSelected).ToList();
		Databases.Clear();
		foreach (var item in ordered)
		{
			Databases.Add(item);
		}
	}

	[RelayCommand(CanExecute = nameof(CanRunScript))]
	private async Task ScriptAsync()
	{
		if (string.IsNullOrWhiteSpace(BaseOutputDirectory))
		{
			Status = "Choose an output directory first.";
			return;
		}

		var targets = Databases.Where(item => item.IsSelected).ToList();
		if (targets.Count == 0)
		{
			Status = "Select at least one database.";
			return;
		}

		ReorderCheckedFirst();

		IsRunning = true;
		IsInErrorState = false;
		Status = "Starting...";
		DurationText = "";
		OverallProgressPercent = 0;
		Warnings.Clear();
		_operationCompletionTcs = new TaskCompletionSource();

		var started = DateTime.Now;
		var cts = new CancellationTokenSource();
		_cts = cts;

		using var elapsedTimer = new System.Timers.Timer(1000);
		elapsedTimer.Elapsed += (_, _) =>
		{
			var elapsed = DateTime.Now.Subtract(started).ToString(@"hh\:mm\:ss");
			Dispatcher.UIThread.Post(() => DurationText = elapsed);
		};
		elapsedTimer.Start();

		try
		{
			var mode = await ResolveScriptingModeAsync(targets, cts.Token);
			if (mode is null)
			{
				Status = "Cancelled.";
				return;
			}

			// Check every selected database for encrypted modules up front, before any scripting
			// starts, and ask for consent (if needed) exactly once - otherwise a long unattended
			// run silently stalls on whichever database first turns out to have one, however deep
			// into the batch that happens to be.
			Status = $"Checking {targets.Count} database(s) for encrypted modules...";
			var totalEncrypted = 0;
			foreach (var target in targets)
			{
				cts.Token.ThrowIfCancellationRequested();
				totalEncrypted += await _scriptingService.CountEncryptedObjectsAsync(_connectionString, target.Name, cts.Token);
			}

			var allowEncryptedModuleDecrypt = false;
			if (totalEncrypted > 0)
			{
				allowEncryptedModuleDecrypt = await RequestEncryptedConsentAsync($"{targets.Count} selected database(s)", totalEncrypted);
				if (!allowEncryptedModuleDecrypt)
				{
					Status = "Cancelled (encrypted modules declined).";
					return;
				}
			}

			var completed = 0;
			var normalizedNameTotal = 0;
			foreach (var item in targets)
			{
				cts.Token.ThrowIfCancellationRequested();
				item.BeginScripting();

				try
				{
					var result = await ScriptOneDatabaseWithConsentAsync(item, mode.Value, completed, targets.Count, allowEncryptedModuleDecrypt, cts.Token);
					item.FinalOutputDirectory = result.OutputDirectory;
					normalizedNameTotal += result.NormalizedConstraintNameCount;
					item.CompleteScripting();
				}
				catch (OperationCanceledException)
				{
					item.CancelScripting();
					throw;
				}
				catch (Exception ex)
				{
					item.FailScripting($"Failed: {ex.Message}");
					throw;
				}

				completed++;
				Status = $"{completed} / {targets.Count} databases completed.";
			}

			Status = NormalizeAutoGeneratedNames
				? $"Complete. {normalizedNameTotal} auto-generated constraint name(s) normalized."
				: "Complete.";
			OverallProgressPercent = 100;
		}
		catch (OperationCanceledException)
		{
			Status = "Cancelled.";
			MarkRemainingCancelled(targets);
		}
		catch (Exception ex)
		{
			IsInErrorState = true;
			Status = $"FAIL: {ex.Message}";
			MarkRemainingCancelled(targets);
		}
		finally
		{
			elapsedTimer.Stop();
			_cts = null;
			IsRunning = false;
			_operationCompletionTcs?.TrySetResult();
			_operationCompletionTcs = null;
		}
	}

	// See FactoryBase.OnDockableClosing (Dock.Model) - returning false here blocks the close (X
	// button, Ctrl+W, and the "Close Document" menu item all funnel through this one hook)
	// without cancelling anything yet, and ConfirmCloseWhileRunningAsync re-issues the close
	// itself once the user actually confirms and the run has stopped.
	public override bool OnClose()
	{
		if (!IsRunning)
		{
			return true;
		}

		if (_closeConfirmationTcs is null)
		{
			_ = ConfirmCloseWhileRunningAsync();
		}

		return false;
	}

	private async Task ConfirmCloseWhileRunningAsync()
	{
		_closeConfirmationTcs = new TaskCompletionSource<bool>();
		PendingCloseConfirmation = true;
		var confirmed = await _closeConfirmationTcs.Task;
		PendingCloseConfirmation = false;
		_closeConfirmationTcs = null;

		if (!confirmed)
		{
			return;
		}

		Cancel();
		if (_operationCompletionTcs is { } completion)
		{
			await completion.Task;
		}

		Factory?.CloseDockable(this);
	}

	[RelayCommand]
	private void ConfirmClose() => _closeConfirmationTcs?.TrySetResult(true);

	[RelayCommand]
	private void KeepWorking() => _closeConfirmationTcs?.TrySetResult(false);

	[RelayCommand(CanExecute = nameof(IsRunning))]
	private void Cancel()
	{
		_cts?.Cancel();
	}

	[RelayCommand]
	private void ChooseDelta()
	{
		PendingOutputConflict = false;
		_outputConflictTcs?.TrySetResult(ScriptOutputConflictChoice.Delta);
	}

	[RelayCommand]
	private void ChooseReset()
	{
		PendingOutputConflict = false;
		_outputConflictTcs?.TrySetResult(ScriptOutputConflictChoice.Reset);
	}

	[RelayCommand]
	private void ChooseCancelConflict()
	{
		PendingOutputConflict = false;
		_outputConflictTcs?.TrySetResult(ScriptOutputConflictChoice.Cancel);
	}

	/// <summary>
	/// Checks each target database's output folder for existing content and, if any is found,
	/// asks the user (in-tab overlay, Delta is the default/Enter choice) whether to only
	/// re-script changed objects, wipe and do a full re-script, or cancel. Returns null on
	/// Cancel.
	/// </summary>
	private async Task<ScriptingMode?> ResolveScriptingModeAsync(
		List<DatabaseListItem> targets,
		CancellationToken cancellationToken)
	{
		var nonEmptyFolders = CollectNonEmptyOutputFolders(targets);
		if (nonEmptyFolders.Count == 0)
		{
			return ScriptingMode.Full;
		}

		var choice = await RequestScriptOutputConflictChoiceAsync(nonEmptyFolders);
		cancellationToken.ThrowIfCancellationRequested();

		if (choice == ScriptOutputConflictChoice.Cancel)
		{
			return null;
		}

		if (choice == ScriptOutputConflictChoice.Reset)
		{
			foreach (var folder in nonEmptyFolders)
			{
				OutputFolderInspector.ClearContents(folder);
			}

			return ScriptingMode.Full;
		}

		return ScriptingMode.Delta;
	}

	private List<string> CollectNonEmptyOutputFolders(IEnumerable<DatabaseListItem> targets)
	{
		List<string> nonEmpty = [];
		foreach (var item in targets)
		{
			var outputDirectory = DatabaseOutputPathResolver.ResolveDatabaseOutputDirectory(
				BaseOutputDirectory,
				_actualServerName,
				item.Name);
			if (OutputFolderInspector.HasContents(outputDirectory))
			{
				nonEmpty.Add(outputDirectory);
			}
		}

		return nonEmpty;
	}

	private Task<ScriptOutputConflictChoice> RequestScriptOutputConflictChoiceAsync(List<string> nonEmptyFolders)
	{
		var tcs = new TaskCompletionSource<ScriptOutputConflictChoice>();
		_outputConflictTcs = tcs;
		PendingOutputConflictFolders = string.Join(Environment.NewLine, nonEmptyFolders);
		PendingOutputConflict = true;
		return tcs.Task;
	}

	[RelayCommand]
	private void ConfirmDecrypt()
	{
		PendingEncryptedConsent = false;
		_encryptedConsentTcs?.TrySetResult(true);
	}

	[RelayCommand]
	private void DeclineDecrypt()
	{
		PendingEncryptedConsent = false;
		_encryptedConsentTcs?.TrySetResult(false);
	}

	// Passed to the engine only when ReformatSqlCode is checked - it stays agnostic of any
	// specific formatter otherwise. Reads FormattingSettingsService live (not captured once)
	// so it matches whatever the user currently has set for paren placement, same as every
	// other reformatting call site in this app. Objects within a database are scripted
	// concurrently (see DatabaseScriptingService.ScriptNormalObjects), so this can be invoked
	// from multiple worker threads at once - AddWarning marshals onto the UI thread rather than
	// mutating the Warnings collection directly here (ObservableCollection isn't thread-safe).
	private string FormatSqlText(string sql, string databaseName, string objectName)
	{
		var result = _sqlCanonicalizationService.FormatForDisplayWithPositions(sql, FormattingSettingsService.OpeningParenOnNewLine);
		if (!result.SafetyCheckPassed)
		{
			AddWarning(new FormattingWarning(databaseName, objectName, result.OriginalTextSnippet ?? "", result.RejectedTextSnippet ?? ""));
		}

		return result.Text;
	}

	private void AddWarning(FormattingWarning warning)
	{
		Dispatcher.UIThread.Post(() => Warnings.Add(warning));
	}

	/// <summary>
	/// Plain-text dump of every current warning, original and problematic text included in full -
	/// meant to be pasted straight into a bug report or an AI coding assistant, not just a summary
	/// line per object. Pure text building (no Avalonia dependency) so the actual clipboard write
	/// stays in the view's code-behind, matching how OnBrowseClick keeps StorageProvider there.
	/// </summary>
	public string BuildWarningsReportText()
	{
		var sb = new StringBuilder();
		foreach (var warning in Warnings)
		{
			sb.Append("=== ").Append(warning.DatabaseName).Append('.').Append(warning.ObjectName).AppendLine(" ===");
			sb.AppendLine("--- ORIGINAL ---");
			sb.AppendLine(warning.OriginalText);
			sb.AppendLine("--- PROBLEMATIC (REFORMATTED) ---");
			sb.AppendLine(warning.ProblematicText);
			sb.AppendLine();
		}

		return sb.ToString();
	}

	private async Task<ScriptDatabaseResult> ScriptOneDatabaseWithConsentAsync(
		DatabaseListItem item,
		ScriptingMode mode,
		int completedDatabases,
		int totalDatabases,
		bool allowEncryptedModuleDecrypt,
		CancellationToken cancellationToken)
	{
		while (true)
		{
			var progress = new Progress<ScriptingProgressReport>(report =>
				ApplyDatabaseProgress(item, report, completedDatabases, totalDatabases));

			var request = new ScriptDatabaseRequest(
				_connectionString,
				item.Name,
				BaseOutputDirectory,
				ScriptingDefaults.MaxConcurrentObjectScripts,
				mode,
				progress,
				outputDirectory => Dispatcher.UIThread.Post(() => item.FinalOutputDirectory = outputDirectory),
				cancellationToken,
				allowEncryptedModuleDecrypt,
				ReformatSqlCode ? (sql, objectName) => FormatSqlText(sql, item.Name, objectName) : null,
				NormalizeAutoGeneratedNames);

			try
			{
				return await _scriptingService.ScriptDatabaseAsync(request);
			}
			catch (EncryptedModulesConsentRequiredException consent)
			{
				// Defensive fallback only - the upfront check in ScriptAsync already asks once for
				// every selected database before this loop ever starts, so this normally never
				// fires. Left in case an object becomes encrypted between that check and actually
				// reaching it here.
				var accepted = await RequestEncryptedConsentAsync($"Database '{consent.DatabaseName}'", consent.EncryptedCount);
				if (!accepted)
				{
					throw new OperationCanceledException("Encrypted module decrypt declined.", cancellationToken);
				}

				allowEncryptedModuleDecrypt = true;
			}
		}
	}

	private Task<bool> RequestEncryptedConsentAsync(string scopeDescription, int encryptedCount)
	{
		_encryptedConsentTcs = new TaskCompletionSource<bool>();
		Dispatcher.UIThread.Post(() =>
		{
			PendingEncryptedScopeDescription = scopeDescription;
			PendingEncryptedCount = encryptedCount;
			PendingEncryptedConsent = true;
		});
		return _encryptedConsentTcs.Task;
	}

	private void ApplyDatabaseProgress(
		DatabaseListItem item,
		ScriptingProgressReport report,
		int completedDatabases,
		int totalDatabases)
	{
		Dispatcher.UIThread.Post(() =>
		{
			if (!item.IsBusy)
			{
				return;
			}

			var databaseFraction = report.TotalObjects == 0
				? 1
				: (double)report.CompletedObjects / report.TotalObjects;
			OverallProgressPercent = 100.0 * (completedDatabases + databaseFraction) / totalDatabases;
			Status = $"{report.DatabaseName}: {report.CompletedObjects} / {report.TotalObjects} objects, {report.ParallelTasks} parallel " +
				$"({completedDatabases + 1}/{totalDatabases} DBs)";
			item.ReportProgress(
				report.TotalObjects == 0 ? 100 : 100.0 * report.CompletedObjects / report.TotalObjects,
				$"{report.CompletedObjects} / {report.TotalObjects} completed, {report.ParallelTasks} parallel.");
		});
	}

	private static void MarkRemainingCancelled(IEnumerable<DatabaseListItem> targets)
	{
		foreach (var item in targets.Where(db => db.IsBusy))
		{
			item.CancelScripting();
		}
	}
}
