using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.SqlServer.TransactSql.ScriptDom;

namespace SqlPhanos.ScriptDatabases;

public sealed record AutoGeneratedConstraintNameNormalizationResult(string Sql, int RenamedCount);

/// <summary>
/// Rewrites SQL Server's own auto-generated constraint names (PK/UQ/FK/DF/CK followed by a
/// hex suffix derived from object_id) to a stable, deterministic name built from the
/// constraint's actual columns - so scripting the same database on two different days doesn't
/// produce a false-positive diff on every nightly-recreated table's default-named PK. For
/// comparison purposes only; not a rename that gets applied back to the server.
/// </summary>
public static class AutoGeneratedConstraintNameNormalizer
{
    // SQL Server's own shape for an unnamed constraint: PREFIX__<truncated parent name(s)>__<hex>.
    // The observed hex suffix length varies by constraint type/SQL Server version, so this is
    // deliberately permissive on that count (8-16) rather than pinned to an exact digit count -
    // it's still specific enough (prefix + double underscore + an all-hex trailing block) that a
    // genuinely human-chosen name is vanishingly unlikely to accidentally match it.
    private static readonly Regex AutoGeneratedNamePattern = new(
        @"^(PK|FK|DF|UQ|CK)__.+__[0-9A-F]{8,16}$",
        RegexOptions.Compiled);

    public static AutoGeneratedConstraintNameNormalizationResult Normalize(string sql, string tableName)
    {
        var parser = new TSql160Parser(false);
        TSqlFragment fragment;
        using (var reader = new StringReader(sql))
        {
            fragment = parser.Parse(reader, out var errors);
            if (errors is { Count: > 0 })
            {
                // Can't safely rewrite text that didn't parse cleanly - leave it exactly as
                // scripted rather than risk corrupting it.
                return new AutoGeneratedConstraintNameNormalizationResult(sql, 0);
            }
        }

        var collector = new ConstraintRenameCollector(tableName);
        fragment.Accept(collector);

        if (collector.Edits.Count == 0)
        {
            return new AutoGeneratedConstraintNameNormalizationResult(sql, 0);
        }

        return new AutoGeneratedConstraintNameNormalizationResult(
            ApplyEdits(sql, collector.Edits),
            collector.Edits.Count);
    }

    private static string ApplyEdits(string sql, List<NameEdit> edits)
    {
        var ordered = edits.OrderBy(edit => edit.StartOffset).ToList();
        var result = new StringBuilder(sql.Length + 32);
        var cursor = 0;
        foreach (var edit in ordered)
        {
            result.Append(sql, cursor, edit.StartOffset - cursor);
            result.Append(edit.NewText);
            cursor = edit.StartOffset + edit.Length;
        }

        result.Append(sql, cursor, sql.Length - cursor);
        return result.ToString();
    }

    private readonly record struct NameEdit(int StartOffset, int Length, string NewText);

    private sealed class ConstraintRenameCollector(string tableName) : TSqlFragmentVisitor
    {
        private readonly Dictionary<string, int> _usedNames = new(StringComparer.OrdinalIgnoreCase);

        // DefaultConstraintDefinition.Column is only populated for the standalone
        // "ALTER TABLE ADD CONSTRAINT ... FOR <column>" form - for the far more common inline
        // "[Col] [int] CONSTRAINT [DF_...] DEFAULT (0)" form it's null, so that case is instead
        // handled from Visit(ColumnDefinition), which knows its own column name. This set stops
        // the generic ConstraintDefinition visit below from also (mis-)handling the same node.
        private readonly HashSet<DefaultConstraintDefinition> _handledInlineDefaults =
            new(ReferenceEqualityComparer.Instance);

        public List<NameEdit> Edits { get; } = [];

        public override void Visit(ColumnDefinition node)
        {
            if (node.DefaultConstraint is not { } defaultConstraint)
            {
                return;
            }

            _handledInlineDefaults.Add(defaultConstraint);
            var columnName = node.ColumnIdentifier?.Value;
            TryRegisterEdit(defaultConstraint, Compose("DF", columnName is null ? [] : [columnName]));
        }

        public override void Visit(ConstraintDefinition node)
        {
            if (node is DefaultConstraintDefinition alreadyHandled
                && _handledInlineDefaults.Contains(alreadyHandled))
            {
                return;
            }

            TryRegisterEdit(node, BuildBaseName(node));
        }

        private void TryRegisterEdit(ConstraintDefinition node, string? baseName)
        {
            var identifier = node.ConstraintIdentifier;
            if (identifier is null || !AutoGeneratedNamePattern.IsMatch(identifier.Value) || baseName is null)
            {
                return;
            }

            var uniqueName = Disambiguate(baseName);
            var newText = Quote(uniqueName, identifier.QuoteType);
            Edits.Add(new NameEdit(identifier.StartOffset, identifier.FragmentLength, newText));
        }

        private string? BuildBaseName(ConstraintDefinition node)
        {
            return node switch
            {
                UniqueConstraintDefinition unique => BuildUniqueName(unique),
                ForeignKeyConstraintDefinition foreignKey => BuildForeignKeyName(foreignKey),
                DefaultConstraintDefinition defaultConstraint => BuildDefaultName(defaultConstraint),
                CheckConstraintDefinition check => BuildCheckName(check),
                _ => null
            };
        }

        private string BuildUniqueName(UniqueConstraintDefinition unique)
        {
            var prefix = unique.IsPrimaryKey ? "PK" : "UQ";
            var columns = unique.Columns
                .Select(column => LastIdentifierValue(column.Column?.MultiPartIdentifier))
                .Where(name => name is not null)
                .Select(name => name!);
            return Compose(prefix, columns);
        }

        private string BuildForeignKeyName(ForeignKeyConstraintDefinition foreignKey)
        {
            var childColumns = foreignKey.Columns.Select(column => column.Value);
            var parentTable = foreignKey.ReferenceTableName?.BaseIdentifier?.Value;
            var parts = parentTable is null ? childColumns : childColumns.Append(parentTable);
            return Compose("FK", parts);
        }

        private string BuildDefaultName(DefaultConstraintDefinition defaultConstraint)
        {
            var column = defaultConstraint.Column?.Value;
            return Compose("DF", column is null ? [] : [column]);
        }

        private string BuildCheckName(CheckConstraintDefinition check)
        {
            var columnCollector = new ColumnReferenceCollector();
            check.CheckCondition.Accept(columnCollector);
            var columns = columnCollector.ColumnNames
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(name => name, StringComparer.OrdinalIgnoreCase);
            return Compose("CK", columns);
        }

        private string Compose(string prefix, IEnumerable<string> parts)
        {
            var joined = string.Join("_", parts);
            var name = string.IsNullOrEmpty(joined)
                ? $"{prefix}_{tableName}"
                : $"{prefix}_{tableName}_{joined}";

            const int maxIdentifierLength = 128;
            return name.Length > maxIdentifierLength ? name[..maxIdentifierLength] : name;
        }

        private string Disambiguate(string baseName)
        {
            if (!_usedNames.TryGetValue(baseName, out var count))
            {
                _usedNames[baseName] = 1;
                return baseName;
            }

            count++;
            _usedNames[baseName] = count;
            return $"{baseName}_{count}";
        }

        private static string? LastIdentifierValue(MultiPartIdentifier? multiPartIdentifier)
        {
            return multiPartIdentifier is { Identifiers.Count: > 0 }
                ? multiPartIdentifier.Identifiers[^1].Value
                : null;
        }

        private static string Quote(string name, QuoteType quoteType)
        {
            return quoteType switch
            {
                QuoteType.SquareBracket => $"[{name}]",
                QuoteType.DoubleQuote => $"\"{name}\"",
                _ => name
            };
        }
    }

    private sealed class ColumnReferenceCollector : TSqlFragmentVisitor
    {
        public List<string> ColumnNames { get; } = [];

        public override void Visit(ColumnReferenceExpression node)
        {
            var name = node.MultiPartIdentifier is { Identifiers.Count: > 0 }
                ? node.MultiPartIdentifier.Identifiers[^1].Value
                : null;
            if (name is not null)
            {
                ColumnNames.Add(name);
            }
        }
    }
}
