using System;
using System.Threading;

namespace SqlPhanos.ScriptDatabases;

public sealed record ScriptDatabaseRequest(
    string ConnectionString,
    string DatabaseName,
    string BaseOutputDirectory,
    int MaxConcurrentObjectScripts,
    ScriptingMode Mode,
    IProgress<ScriptingProgressReport> Progress,
    Action<string> OnOutputDirectoryResolved,
    CancellationToken CancellationToken,
    bool AllowEncryptedModuleDecrypt = false,
    // Deliberately just a text transform (plus the object name, purely for the caller's own
    // logging - this engine never inspects it), not a reference to any specific formatter -
    // keeps this engine agnostic of (and not dependent on) SqlPhanos.CodeFormatting. Null means
    // "write scripts exactly as SMO/the decryptor produced them," which is also the default.
    Func<string, string, string>? FormatSqlText = null,
    // Rewrites SQL Server's auto-generated PK/UQ/FK/DF/CK constraint names (see
    // AutoGeneratedConstraintNameNormalizer) to a deterministic name built from the constraint's
    // own columns - for comparison purposes only. Unlike FormatSqlText, this is implemented
    // entirely within this engine (ScriptDom is a neutral SQL parser, not an opinionated
    // formatter, so depending on it directly doesn't compromise self-containment).
    bool NormalizeAutoGeneratedNames = false);

public sealed record ScriptDatabaseResult(
    string OutputDirectory,
    string ServerOutputDirectory,
    int NormalizedConstraintNameCount = 0);
