using SqlPhanos.ScriptDatabases;
using Xunit;

namespace SqlPhanos.ScriptDatabases.Tests;

public class AutoGeneratedConstraintNameNormalizerTests
{
    [Fact]
    public void Normalize_RewritesAutoGeneratedPrimaryKeyUsingItsColumns()
    {
        var sql = """
            CREATE TABLE [dbo].[Orders](
                [OrderID] [int] NOT NULL,
                [LineNo] [int] NOT NULL,
                CONSTRAINT [PK__Orders__3213E83F1A2B3C4D] PRIMARY KEY CLUSTERED ([OrderID] ASC, [LineNo] ASC)
            )
            """;

        var result = AutoGeneratedConstraintNameNormalizer.Normalize(sql, "Orders");

        Assert.Equal(1, result.RenamedCount);
        Assert.Contains("[PK_Orders_OrderID_LineNo]", result.Sql);
        Assert.DoesNotContain("PK__Orders__3213E83F1A2B3C4D", result.Sql);
    }

    [Fact]
    public void Normalize_LeavesUserChosenNamesUntouched()
    {
        var sql = """
            CREATE TABLE [dbo].[Orders](
                [OrderID] [int] NOT NULL,
                CONSTRAINT [PK_Orders_MyOwnName] PRIMARY KEY CLUSTERED ([OrderID] ASC)
            )
            """;

        var result = AutoGeneratedConstraintNameNormalizer.Normalize(sql, "Orders");

        Assert.Equal(0, result.RenamedCount);
        Assert.Equal(sql, result.Sql);
    }

    [Fact]
    public void Normalize_RewritesDefaultConstraintUsingItsColumn()
    {
        var sql = """
            CREATE TABLE [dbo].[Orders](
                [Status] [int] NOT NULL CONSTRAINT [DF__Orders__Status__1A2B3C4D] DEFAULT ((0))
            )
            """;

        var result = AutoGeneratedConstraintNameNormalizer.Normalize(sql, "Orders");

        Assert.Equal(1, result.RenamedCount);
        Assert.Contains("[DF_Orders_Status]", result.Sql);
    }

    [Fact]
    public void Normalize_RewritesCheckConstraintUsingReferencedColumnsSorted()
    {
        var sql = """
            CREATE TABLE [dbo].[Orders](
                [StartDate] [date] NOT NULL,
                [EndDate] [date] NOT NULL,
                CONSTRAINT [CK__Orders__1A2B3C4D] CHECK (([EndDate]>[StartDate]))
            )
            """;

        var result = AutoGeneratedConstraintNameNormalizer.Normalize(sql, "Orders");

        Assert.Equal(1, result.RenamedCount);
        Assert.Contains("[CK_Orders_EndDate_StartDate]", result.Sql);
    }

    [Fact]
    public void Normalize_RewritesForeignKeyUsingChildColumnsAndParentTable()
    {
        var sql = """
            ALTER TABLE [dbo].[OrderLines] WITH CHECK ADD CONSTRAINT [FK__OrderLine__Order__1A2B3C4D] FOREIGN KEY([OrderID])
            REFERENCES [dbo].[Orders] ([OrderID])
            """;

        var result = AutoGeneratedConstraintNameNormalizer.Normalize(sql, "OrderLines");

        Assert.Equal(1, result.RenamedCount);
        Assert.Contains("[FK_OrderLines_OrderID_Orders]", result.Sql);
    }

    [Fact]
    public void Normalize_DisambiguatesCollidingGeneratedNames()
    {
        var sql = """
            CREATE TABLE [dbo].[Orders](
                [A] [int] NOT NULL,
                [B] [int] NOT NULL,
                CONSTRAINT [UQ__Orders__1A2B3C4D] UNIQUE ([A]),
                CONSTRAINT [UQ__Orders__2B3C4D5E] UNIQUE ([A])
            )
            """;

        var result = AutoGeneratedConstraintNameNormalizer.Normalize(sql, "Orders");

        Assert.Equal(2, result.RenamedCount);
        Assert.Contains("[UQ_Orders_A]", result.Sql);
        Assert.Contains("[UQ_Orders_A_2]", result.Sql);
    }
}
